#!/usr/bin/env python3
"""
build_catalog.py - Generates CATALOG.md and profiles.json from the skill frontmatter.

The source of truth is the frontmatter of every SKILL.md:

    metadata:
      profiles: core, laravel        # one or more profiles declared by the author
      scope: global                  # global | project  (where it gets installed)

This script decides nothing: it reads what the author declared, builds the index
and, with --check, fails when something does not add up (a skill with no profile,
an unknown profile, a stale catalog). The criteria for choosing profile and scope
are in CONTRIBUTING.md.

Usage:
    python3 scripts/build_catalog.py            # regenerate CATALOG.md and profiles.json
    python3 scripts/build_catalog.py --check    # verify they are up to date (CI)
    python3 scripts/build_catalog.py --json     # print the index without writing

Exit code: 0 ok | 1 consistency problems (or files to regenerate) | 2 execution error
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
CATALOG = ROOT / "CATALOG.md"
PROFILES = ROOT / "profiles.json"
REPO = "padosoft/skills"

#: Allowed profiles. Adding one is an explicit decision: this tuple is edited in a PR,
#: so the birth of a profile goes through review like any other choice.
KNOWN_PROFILES: tuple[str, ...] = (
    "core", "laravel", "node", "react-native", "email", "api", "payments", "data", "devops",
    "ai",
)
KNOWN_SCOPES: tuple[str, ...] = ("global", "project")

GENERATED_START = "<!-- CATALOG:START - generated by scripts/build_catalog.py, do not edit by hand -->"
GENERATED_END = "<!-- CATALOG:END -->"


@dataclass
class Skill:
    name: str
    path: Path
    description: str
    version: str = ""
    profiles: list[str] = field(default_factory=list)
    scope: str = ""
    tagline: str = ""

    @property
    def rel(self) -> str:
        return self.path.relative_to(ROOT).as_posix()

    @property
    def install_url(self) -> str:
        return f"https://github.com/{REPO}/tree/main/{self.rel}"

    @property
    def full_description(self) -> str:
        """Description collapsed onto a single line, for the detail card."""
        return " ".join(self.description.split())

    @property
    def summary(self) -> str:
        """The author's one-line statement of the rule; the description's first sentence as a fallback."""
        if self.tagline:
            return self.tagline
        first = re.split(r"(?<=[.:])\s", self.description.strip(), maxsplit=1)[0]
        return (first[:160] + "…") if len(first) > 160 else first


def parse_frontmatter(text: str) -> dict[str, str]:
    """Minimal YAML frontmatter: top-level keys + indented metadata blocks."""
    if not text.startswith("---\n"):
        raise ValueError("missing frontmatter")
    end = text.find("\n---\n", 3)
    if end == -1:
        raise ValueError("unterminated frontmatter")
    out: dict[str, str] = {}
    key: str | None = None
    buf: list[str] = []
    meta_prefix = False

    def flush() -> None:
        if key:
            out[key] = " ".join(x.strip() for x in buf).strip()

    for raw in text[4:end + 1].splitlines():
        if not raw.strip():
            continue
        if raw.startswith((" ", "\t")):
            if meta_prefix:
                m = re.match(r"^\s+([A-Za-z0-9_-]+):\s*(.*)$", raw)
                if m:
                    flush()
                    key, value = f"metadata.{m.group(1)}", m.group(2).strip()
                    buf = [value] if value else []
                    continue
            buf.append(raw)
            continue
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", raw)
        if not m:
            raise ValueError(f"invalid line in frontmatter: {raw!r}")
        flush()
        key, value = m.group(1), m.group(2).strip()
        meta_prefix = key == "metadata"
        buf = [] if value in (">", ">-", "|", "|-", "") else [value]
    flush()
    return out


def load_skills() -> tuple[list[Skill], list[str]]:
    """Reads every skill; returns (skills, problems)."""
    skills: list[Skill] = []
    problems: list[str] = []

    for skill_md in sorted(SKILLS_DIR.glob("*/SKILL.md")):
        try:
            fm = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        except ValueError as exc:
            problems.append(f"{skill_md.relative_to(ROOT)}: {exc}")
            continue

        name = fm.get("name", "")
        folder = skill_md.parent.name
        if name != folder:
            problems.append(f"{folder}: 'name' ({name!r}) differs from the folder")

        profiles = [p.strip() for p in fm.get("metadata.profiles", "").replace(",", " ").split() if p.strip()]
        scope = fm.get("metadata.scope", "").strip()

        # Guard: every skill declares at least one valid profile and a valid scope
        if not profiles:
            problems.append(f"{folder}: missing 'metadata.profiles' (see CONTRIBUTING.md)")
        for p in profiles:
            if p not in KNOWN_PROFILES:
                problems.append(f"{folder}: unknown profile '{p}' (allowed: {', '.join(KNOWN_PROFILES)})")
        if scope not in KNOWN_SCOPES:
            problems.append(f"{folder}: 'metadata.scope' must be global or project (found {scope!r})")
        if scope == "global" and "core" not in profiles:
            problems.append(f"{folder}: scope global requires the 'core' profile")

        skills.append(Skill(
            name=name or folder,
            path=skill_md.parent,
            description=fm.get("description", "").strip(),
            version=fm.get("metadata.version", "").strip(),
            profiles=profiles,
            scope=scope,
            tagline=fm.get("metadata.summary", "").strip().strip('"'),
        ))

    if not skills:
        problems.append("no skill found in skills/*/SKILL.md")
    return skills, problems


def build_profiles(skills: list[Skill]) -> dict[str, object]:
    by_profile: dict[str, list[str]] = {p: [] for p in KNOWN_PROFILES}
    for s in skills:
        for p in s.profiles:
            if p in by_profile:
                by_profile[p].append(s.name)
    return {
        "repo": REPO,
        "profiles": {p: sorted(v) for p, v in by_profile.items() if v},
        "scope": {s.name: s.scope for s in sorted(skills, key=lambda x: x.name)},
    }


def build_catalog(skills: list[Skill], profiles: dict) -> str:
    lines: list[str] = [GENERATED_START, ""]
    lines.append(f"_{len(skills)} skills · index generated automatically, do not edit by hand._\n")
    lines.append("| Skill | Profiles | Scope | What it does |")
    lines.append("|---|---|---|---|")
    for s in sorted(skills, key=lambda x: x.name):
        lines.append(f"| [`{s.name}`]({s.install_url}) | {', '.join(s.profiles)} | {s.scope} | {s.summary} |")
    lines.append("")
    lines.append("## Profiles")
    lines.append("")
    for p, names in profiles["profiles"].items():
        lines.append(f"- **{p}** — {', '.join(f'`{n}`' for n in names)}")
    lines.append("")
    lines.append("## Install by profile")
    lines.append("")
    lines.append("```bash")
    lines.append("./scripts/install-profile.sh core --global      # cross-project, on every project")
    lines.append("./scripts/install-profile.sh laravel email      # the stack of this project")
    lines.append("```")
    lines.append("")
    lines.append("## Install a single skill")
    lines.append("")
    lines.append("```bash")
    for s in sorted(skills, key=lambda x: x.name):
        lines.append(f"npx skills add {s.install_url}")
    lines.append("```")
    lines.append("")
    lines.append(GENERATED_END)
    return "\n".join(lines) + "\n"


README = ROOT / "README.md"
README_START = "<!-- SKILLS:START - generated by scripts/build_catalog.py, do not edit by hand -->"
README_END = "<!-- SKILLS:END -->"
DETAIL_START = "<!-- SKILLS_DETAIL:START - generated by scripts/build_catalog.py, do not edit by hand -->"
DETAIL_END = "<!-- SKILLS_DETAIL:END -->"

#: What each profile is for, shown in the grouped index. A profile missing from here still renders.
PROFILE_BLURB: dict[str, str] = {
    "core": "installed **globally**, they apply to every project whatever the stack",
    "laravel": "Laravel and PHP applications",
    "node": "Node and Bun services",
    "react-native": "React Native and Expo apps",
    "email": "transactional and marketing HTML email",
    "api": "HTTP APIs, their contracts, and the work they hand off",
    "payments": "anything where money moves and has to balance",
    "data": "the database, and everything read from it in volume",
    "devops": "CI, gates, releases and the scripts around them",
    "ai": "building on a model: agents, tools, retrieval and the corpus behind them",
}


def build_readme_index(skills: list[Skill], profiles: dict) -> str:
    """Grouped by profile: what you actually get when you install one, without scrolling the catalog."""
    lines: list[str] = [README_START, ""]
    lines.append(f"_{len(skills)} skills across {len(profiles['profiles'])} profiles, grouped by what you "
                 "install. A skill that belongs to two profiles appears in both. The complete list with "
                 "descriptions is [at the end](#every-skill-one-by-one); `make catalog` refreshes both._")
    lines.append("")
    for profile, names in profiles["profiles"].items():
        members = sorted((s for s in skills if s.name in set(names)), key=lambda x: x.name)
        blurb = PROFILE_BLURB.get(profile, "")
        count = f"{len(members)} skill" + ("s" if len(members) != 1 else "")
        lines.append(f"### `{profile}` — {count}" + (f" · {blurb}" if blurb else ""))
        lines.append("")
        lines.append("| Skill | The rule | Scope |")
        lines.append("|---|---|---|")
        for s in members:
            anchor = s.name.replace("padosoft-", "")
            lines.append(f"| [`{s.name}`](#{anchor}) | {s.summary} | {s.scope} |")
        lines.append("")
        lines.append("```bash")
        lines.append(f"./scripts/install-profile.sh {profile}" + (" --global" if profile == "core" else ""))
        lines.append("```")
        lines.append("")
    lines.append(README_END)
    return "\n".join(lines) + "\n"


def build_readme_detail(skills: list[Skill]) -> str:
    """The complete reference, alphabetical, at the foot of the README."""
    lines: list[str] = [DETAIL_START, ""]
    lines.append(f"_All {len(skills)} skills in alphabetical order: what each one says, and when it "
                 "triggers. Generated from the frontmatter._")
    lines.append("")
    for s in sorted(skills, key=lambda x: x.name):
        anchor = s.name.replace("padosoft-", "")
        where = ("installed **globally** with the `core` profile: it applies to every project"
                 if s.scope == "global" else
                 "installed **in the project** that needs it, not globally")
        lines.append(f"### {anchor}")
        lines.append("")
        lines.append(f"**{s.summary}**")
        lines.append("")
        lines.append(f"`{s.name}` · profiles: {', '.join(f'`{p}`' for p in s.profiles)} · "
                     f"scope: `{s.scope}` · version: {s.version or '—'}")
        lines.append("")
        lines.append(f"**Triggers when** — {s.full_description}")
        lines.append("")
        lines.append(f"**Where it goes** — {where}. Folder: [`{s.rel}`]({s.rel}).")
        lines.append("")
        lines.append("```bash")
        lines.append(f"npx skills add {s.install_url}")
        lines.append("```")
        lines.append("")
    lines.append(DETAIL_END)
    return "\n".join(lines) + "\n"


def _inject(text: str, start: str, end: str, body: str) -> str:
    if start not in text or end not in text:
        return text
    return text.split(start)[0] + body.rstrip("\n") + text.split(end, 1)[1]


def _aligned(text: str, start: str, end: str, body: str) -> bool:
    if start not in text:
        return True
    current = start + text.split(start, 1)[1].split(end, 1)[0] + end
    return current.strip() == body.strip()


def inject_readme(index: str, detail: str) -> None:
    """Rewrites both generated sections of the README, when their markers are present."""
    if not README.is_file():
        return
    text = README.read_text(encoding="utf-8")
    text = _inject(text, README_START, README_END, index)
    text = _inject(text, DETAIL_START, DETAIL_END, detail)
    README.write_text(text, encoding="utf-8", newline="\n")


def check_readme(index: str, detail: str) -> list[str]:
    """Names of the README sections that are out of date."""
    if not README.is_file():
        return []
    text = README.read_text(encoding="utf-8")
    stale = []
    if not _aligned(text, README_START, README_END, index):
        stale.append("README.md (grouped index)")
    if not _aligned(text, DETAIL_START, DETAIL_END, detail):
        stale.append("README.md (skill list)")
    return stale


def wrap_catalog(body: str) -> str:
    header = (
        "# Padosoft skills catalog\n\n"
        "This file is **generated**: it is refreshed by reading the frontmatter of every `SKILL.md`.\n"
        "To change the profile or scope of a skill, edit its frontmatter, not this file.\n\n"
    )
    return header + body


ROUTER = SKILLS_DIR / "padosoft-skills-router" / "SKILL.md"


def inject_router(body: str) -> None:
    """Rewrites the Catalog section of the router skill, when present."""
    if not ROUTER.is_file():
        return
    text = ROUTER.read_text(encoding="utf-8")
    if GENERATED_START not in text or GENERATED_END not in text:
        return
    pre = text.split(GENERATED_START)[0]
    post = text.split(GENERATED_END, 1)[1]
    ROUTER.write_text(pre + body.rstrip("\n") + post, encoding="utf-8", newline="\n")


def check_router(body: str) -> bool:
    """True when the Catalog section of the router is aligned."""
    if not ROUTER.is_file():
        return True
    text = ROUTER.read_text(encoding="utf-8")
    if GENERATED_START not in text:
        return True
    current = GENERATED_START + text.split(GENERATED_START, 1)[1].split(GENERATED_END, 1)[0] + GENERATED_END
    return current.strip() == body.strip()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify without writing (CI)")
    ap.add_argument("--json", action="store_true", help="print the JSON index on stdout")
    args = ap.parse_args()

    try:
        skills, problems = load_skills()
    except Exception as exc:
        print(f"Execution error: {exc}", file=sys.stderr)
        return 2

    profiles = build_profiles(skills)
    catalog = wrap_catalog(build_catalog(skills, profiles))
    profiles_json = json.dumps(profiles, ensure_ascii=False, indent=2) + "\n"

    if args.json:
        print(profiles_json, end="")
        return 1 if problems else 0

    if problems:
        print("Consistency problems:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    if args.check:
        stale = [f.name for f, new in ((CATALOG, catalog), (PROFILES, profiles_json))
                 if not f.is_file() or f.read_text(encoding="utf-8") != new]
        if not check_router(build_catalog(skills, profiles)):
            stale.append("skills/padosoft-skills-router/SKILL.md")
        stale += check_readme(build_readme_index(skills, profiles), build_readme_detail(skills))
        if stale:
            print(f"To regenerate: {', '.join(stale)} — run `make catalog`", file=sys.stderr)
            return 1
        print(f"Catalog up to date: {len(skills)} skills, {len(profiles['profiles'])} profiles")
        return 0

    # newline="\n" on every write: on Windows the default translates to CRLF, against .gitattributes
    CATALOG.write_text(catalog, encoding="utf-8", newline="\n")
    PROFILES.write_text(profiles_json, encoding="utf-8", newline="\n")
    inject_router(build_catalog(skills, profiles))
    inject_readme(build_readme_index(skills, profiles), build_readme_detail(skills))
    print(f"Wrote {CATALOG.name} and {PROFILES.name}: {len(skills)} skills, {len(profiles['profiles'])} profiles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
